### ISSUE TITLE
Team Contract

### ISSUE THREAD

**Issue by erikhuck** [erikhuck/PhylogenyWebsite#1]
The team contract is almost done but it needs to be reformatted. The google doc is here: https://docs.google.com/document/d/141-omtavLQrbo_zm4KA-Q4SWW0qPlguFnq7Z9ozGQaE/edit?usp=sharing

**Comment by erikhuck** [comment]
Something we need to ask Dr. Payne is how exactly he wants this to be "signed". He said he wants a PDF, but how do we get signatures on a PDF? We could type our names at the end, but is that valid? Or we can use a tablet to write our signatures at the bottom of the doc.

**Comment by jbeatty88** [comment]
I think we should keep it digital. I'll bring my Surface to class on Thursday and we can all sign it on there with the pen.
